Various additions
RaphaelIT7/obsolete-source-engine pull request #2
Opened 2024-11-25 02:39 UTC by marchc1

- LUA_PUSH_METATABLE_FUNCTION macro (temporary for now but makes things a bit cleaner)
- __content folder and auto-patcher .bat file
- FindProceduralMaterial's 3rd argument (pVMTKeyValues) now optional for just finding a procedural material
- Add IMaterial lua interface
- Add IMaterial lua interface
- Add Entity:SetMaterial to Lua
- Add LuaHelper::TableToKeyValues (may need to be reworked)
- Implement a basic physgun
- Add the ability to override materials in the engine on entities
- Made the clang format not as annoying (4-tab width)

2024-11-25 06:54 UTC, RaphaelIT7 reviewed
Some things I found while flying over the code

2024-11-25 06:54 UTC, RaphaelIT7 commented on GarrysMod/GModMaterialProxy.cpp
> +		if(g_Lua->PCall(3, 0, 0) == 0){
I would use g_Lua->CallFunctionProtected instead

2024-11-25 06:54 UTC, RaphaelIT7 commented on GarrysMod/Lua/custom_types/lua_material.cpp
> +	const char* shader = LUA->GetString(2);
I think LUA->CheckString would fit better into here

2024-11-25 06:54 UTC, RaphaelIT7 commented on materialsystem/cmaterialsystem.cpp
> +	if (pVMTKeyValues != NULL) {
please wrap #ifdef BUILD_GMOD around this so that I won't accidentally revert this when updating from the main repo

2024-11-25 06:54 UTC, RaphaelIT7 commented on game/server/baseentity.h
> +
I would like if the order was kept so that we can be compatible with the sourcesdk later on

2024-11-25 06:54 UTC, RaphaelIT7 commented on game/server/baseentity.cpp
> +const char *CBaseEntity::GetMaterialOverride() { return m_OverrideMaterial.Get(); }
I think these ones can be a inline function in the baseentity.h file instead like most similar functions

2024-11-25 06:54 UTC, RaphaelIT7 commented on GarrysMod/Lua/LuaHelper.cpp
> +							 const char* function) {
Why are these split into multiple lines?
This does look weird xd (would perfer if it's kept in one line for now but wouldn't be nessesary)

2024-11-25 18:42 UTC, marchc1 commented on GarrysMod/Lua/LuaHelper.cpp
> +							 const char* function) {
My VS2022 won't respect my wishes for code formatting.. very annoying, i'll manually fix it for now

2024-11-25 18:50 UTC, marchc1 commented on GarrysMod/Lua/custom_types/lua_material.cpp
> +	const char* shader = LUA->GetString(2);
I kinda need GetString for the first part because of the ! prefix, not sure what you would suggest

2024-11-26 02:35 UTC, RaphaelIT7 requested changes
These should be the final things

2024-11-26 02:35 UTC, RaphaelIT7 commented on game/client/c_baseentity.cpp
> +{ return m_OverrideMaterial; }
please don't cramp it into a single like, as we do it everywhere like this.
```cpp
const char* CBaseEntity::GetMaterialOverride() 
{
	return m_OverrideMaterial;
}
```

2024-11-26 02:35 UTC, RaphaelIT7 commented on game/client/c_baseentity.cpp
> +		Q_strncpy(m_OverrideMaterial, strMaterial, 255);
why not use sizeof(m_OverrideMaterial) instead of hardcoding the length? would make it easier to adjust in the future

2024-11-26 02:35 UTC, RaphaelIT7 commented on GarrysMod/Lua/custom_types/lua_texture.cpp
> +	if (!LUA->FindOnObjectsMetaTable(-2, -1)) LUA->PushNil();
I think it would look nicer if it's spead into a seperate line like
```cpp
if (!LUA->FindOnObjectsMetaTable(-2, -1))
	LUA->PushNil();
```

2024-11-26 02:35 UTC, RaphaelIT7 commented on GarrysMod/Lua/custom_types/lua_material.cpp
> +	if (!LUA->FindOnObjectsMetaTable(1, 2)) LUA->PushNil();
I think it would look nicer if it's spead into a seperate line like
```cpp
if (!LUA->FindOnObjectsMetaTable(-2, -1))
	LUA->PushNil();
```

2024-11-26 02:35 UTC, RaphaelIT7 commented on GarrysMod/Lua/LuaHelper.cpp
> +								   unsigned long long wsid) {
It did the funny thingy

2024-11-26 02:41 UTC, marchc1 commented on game/client/c_baseentity.cpp
> +		Q_strncpy(m_OverrideMaterial, strMaterial, 255);
Forgot to lol

2024-11-26 02:41 UTC, marchc1 commented on game/client/c_baseentity.cpp
> +{ return m_OverrideMaterial; }
I don't know why it did that

2024-11-26 02:48 UTC, RaphaelIT7 commented on GarrysMod/Lua/custom_types/lua_texture.cpp
> +								"IsErrorTexture");
uuh, just found it also doing the funnies here ._.

2024-11-26 02:50 UTC, RaphaelIT7 approved these changes

2024-11-26 02:50 UTC, merged